version: "3.0"

services:
  simple-rest-server_rss:
    container_name: server 
    build:
      context: .
    env_file:
    - .env
    volumes:
    - .:/app
    ports:
    - ${PORT}:${PORT}
    restart: always
    depends_on: 
    - postgres

  postgres:
    container_name: postgres_db
    image: postgres:14
    build: 
      context: .
    env_file:
    - .env  
    environment:
    -  PG_DATA=/var/lib/postgresql/data
    -  POSTGRES_DB=${DB_POSTGRES}
    -  POSTGRES_USER=${DB_USER}
    -  POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always